### PR TITLE
Fix bugs for attaching files and replace file icon of actions.

### LINKED ISSUE #215: Share button: allow other file types
The :paperclip: button left to the input box only allows sharing of pictures. It would be great to also have sharing of videos (maybe with recompression), and also maybe of other file types like documents etc.

### LINKED ISSUE #256: Allow downloading aesgcm (non image) URLs
When sharing non-image files from Conversations, the recipient gets an aesgcm URL that they can't open. Ideally the file would be downloaded by Monal, decrypted and passed to whatever mechanism iOS has for opening arbitrary files.

### PR DESCRIPTION
**Pull request by poormusic2001**
1. Change the name of the Images action to Files in MacOS.
2. Remove the duplicate image action in iOS.
3. Remove the file_attachment for replacing new images.
4. Add new icon files of the action.

### CODE REVIEW

**Review by FriedrichAltheide — APPROVED** [review]

File: Monal/Classes/chatViewController.m [hunk 1]
```diff
@@ -1126,11 +1127,8 @@ -(IBAction)attach:(id)sender
         }
         [fileAction setValue:[[UIImage imageNamed:@"file-attatchment"] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal] forKey:@"image"];
         [actionControll addAction:cameraAction];
-        [actionControll addAction:photosAction];
```
Comment (tmolitor-stud-tu) [inline Monal/Classes/chatViewController.m:1129]: Why do you remove the photos action in iOS completely?
There are distctinct UIs for photos versus camera versus file.
Or do I miss something here?

**Review by tmolitor-stud-tu — CHANGES_REQUESTED** [review]

File: Monal/Classes/chatViewController.m (hunk 1 above)
Comment (tmolitor-stud-tu) [reply Monal/Classes/chatViewController.m:1129]: Sorry, never mind...my fault :)

**Review by tmolitor-stud-tu — APPROVED** [review]
